---
- name: Configure system
  hosts: vps
  vars_files:
    - vars/public.yml
    - vars/vault.yml
  roles:
    - role: reverse_proxy
    - role: recipes
    - role: backups
    - role: notifications
    - role: artis3n.tailscale.device
    - role: firewall
    - role: hifis.toolkit.unattended_upgrades
      become: true
      unattended_mail: root
    - role: geerlingguy.swap
      become: true
