---
- name: Create open-webui config directory
  become: true
  ansible.builtin.file:
    group: 1000
    mode: "0755"
    owner: 1000
    path: /var/opt/open-webui
    state: directory
- name: Create a Quadlet file
  become: true
  containers.podman.podman_container:
    name: open-webui
    image: ghcr.io/open-webui/open-webui:{{ open_webui_version }}
    state: quadlet
    env:
      WEBUI_URL: https://chat.{{ domain_name }}
      WEBUI_SECRET_KEY: "{{ open_webui_secret_key }}"
      OPENAI_API_KEY: "{{ openai_api_key }}"
      ENABLE_SIGNUP: false
      ENABLE_OPENAI_API: true
      ENABLE_OLLAMA_API: false
      ENABLE_CODE_EXECUTION: false
      ENABLE_CODE_INTERPRETER: false
      ENABLE_EVALUATION_ARENA_MODELS: false
      ENABLE_MESSAGE_RATING: false
      ENABLE_COMMUNITY_SHARING: false
    quadlet_filename: open-webui-container
    network: host
    volumes:
      - /var/opt/open-webui:/app/backend/data:rw
    quadlet_options:
      - AutoUpdate=registry
      - Pull=always
      - |
        [Unit]
        After=network-online.target nss-lookup.target
        [Service]
        Restart=always
        [Install]
        WantedBy=default.target
  notify:
    - Reload systemd for open-webui
    - Restart open-webui
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
