---
- name: Reload systemd for open-webui
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
  changed_when: true
- name: Restart open-webui
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  become: true
  loop: "{{ started_services }}"
